default_context:
  project_name: 'fnaf-api'
  project_slug: 'fnaf-api'
  domain_main: 'fnaf-api.com'
  domain_staging: 'stag.fnaf-api.com'
  docker_swarm_stack_name_main: 'fnaf-api-com'
  docker_swarm_stack_name_staging: 'stag-fnaf-api-com'
  secret_key: 'ef96c558295d10839246baa4ba2fcccd796013791395bdd6e3233381b2484177'
  first_superuser: 'admin@fnaf-api.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fnaf-api.com", "https://stag.fnaf-api.com", "https://fnaf-api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fnaf-api.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'fnaf-api.com'
  traefik_constraint_tag_staging: 'stag.fnaf-api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
